Repository graalvm/graalvm-community-jdk21u, pull requests merged in 2025-05, with the labels that each got.

#60 [Backport] svm: Adopt "JDK-8314794: Improve UTF8 String supports" [GR-58535]
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/io/Utf8.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/Utf8.java
Labels: OCA Verified, amazon-interest

#61 [Backport] [GR-58292] Add option to disable substitutions
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/AnnotationSubstitutionProcessor.java
Labels: OCA Verified, amazon-interest

#68 [Backport] Flip a bit in test input to avoid unspecified NaN behavior in bitcode tests.
  sulong/tests/com.oracle.truffle.llvm.tests.llirtestgen.native/prelude.c
Labels: OCA Verified

#62 [Backport] [GR-58531] Eagerly initialize caches in method handle implementation
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/methodhandles/MethodHandleFeature.java
Labels: OCA Verified, amazon-interest

#65 [GR-60402] Add vzeroupper upon the entrance of AMD64 sha1 and sha256 stubs.
  compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/AMD64SHA1Op.java
  compiler/src/jdk.internal.vm.compiler/src/org/graalvm/compiler/lir/amd64/AMD64SHA256Op.java
Labels: OCA Verified, bellsoft-interest

#80 [Backport][GR-59499] Fix System.getProperties() when called from virtual thread.
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixUtils.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Pwd.java
Labels: OCA Verified

#84 [Backport][GR-63455] Remove pointless parallel stream processing for classpath entries.
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageClassLoaderSupport.java
Labels: OCA Verified
